CREATE TABLE report (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   parcipant_id INTEGER NOT NULL,
   report_type TYPE,
   topic VARCHAR,
   publication EON,
   CONSTRAINT report_pkey PRIMARY KEY (id)
);

CREATE TABLE conference (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR,
   location VARCHAR,
   data TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT conference_pkey PRIMARY KEY (id)
);

CREATE TABLE folders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name TEXT,
   user_id INTEGER,
   CONSTRAINT folders_pkey PRIMARY KEY (id)
);

CREATE TABLE note_images (
  note_id INTEGER,
   url TEXT
);

CREATE TABLE notes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   title TEXT,
   content TEXT,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   user_id INTEGER,
   position INTEGER,
   folder_id INTEGER,
   CONSTRAINT notes_pkey PRIMARY KEY (id)
);

CREATE TABLE participant (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(50),
   surname VARCHAR(50),
   patronymic VARCHAR(50),
   organization VARCHAR,
   country VARCHAR,
   academic_degree VARCHAR,
   CONSTRAINT participant_pkey PRIMARY KEY (id)
);

CREATE TABLE reports_conferences (
  report_id INTEGER,
   conference_id INTEGER
);

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   username TEXT,
   password TEXT,
   role TEXT,
   CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE folders ADD CONSTRAINT folders_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE note_images ADD CONSTRAINT note_images_note_id_fkey FOREIGN KEY (note_id) REFERENCES notes (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE notes ADD CONSTRAINT notes_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES folders (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE notes ADD CONSTRAINT notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE report ADD CONSTRAINT report_parcipant_id_fkey FOREIGN KEY (parcipant_id) REFERENCES participant (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE reports_conferences ADD CONSTRAINT reports_conferences_conference_id_fkey FOREIGN KEY (conference_id) REFERENCES conference (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE reports_conferences ADD CONSTRAINT reports_conferences_report_id_fkey FOREIGN KEY (report_id) REFERENCES report (id) ON UPDATE NO ACTION ON DELETE NO ACTION;